version: "3.9"
services:
  postgresql:
    image: postgres:13  # Adjust the version if needed
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "bank"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgresql_data:/var/lib/postgresql/data  # Volume for persistent data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changeLogFile=master.xml  # Updated option name
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/bank
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./src/main/resources/migrations/:/liquibase/changelog/
    networks:
      - backend

volumes:
  postgresql_data:  # Define a named volume for PostgreSQL data storage

networks:
  backend:  # Define a custom network for the services to communicate
